version: '3.8' 
 
services: 
  postgres: 
    container_name: todo-backend-postgres
    image: postgres 
    ports: 
      - 5432:5432 
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456 
      POSTGRES_DB: tododb
      PGDATA: /data/postgres
    volumes: 
      - ./data/pg:/data/postgres